CREATE TABLE IF NOT EXISTS illusts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type INTEGER NOT NULL,
    type_id INTEGER NOT NULL,
    user INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    downloaded BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type INTEGER NOT NULL,
    type_id INTEGER NOT NULL,
    raw_json TEXT NOT NULL
);
